[package]
name = "penrose_wm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penrose = { git = "https://github.com/sminez/penrose" }
simplelog = "0.11"
tracing = "0.1.29"
